<?php

/**
 * @file
 * This is the file description for GrowCalc module.
 *
 *
 * @author Coder
 */


/**
 * Implements hook_permission()
 */
function growcalc_permission() {
  $permissions = array(
    'administer growcalc' => array(
      'title' => t('Administer GrowCalc'),
      'description' => t('Configure GrowCalc.')
    ),
  );
  return $permissions;
}

/**
 * Implements hook_menu()
 */
function growcalc_menu() {
  $items['growcalc'] = array(
    'title' => 'GrowCalc',
    'page callback' => 'growcalc_info_page',
    'access callback' => TRUE,
  );

  $items['admin/config/growcalc'] = array(
    'title' => 'GrowCalc',
    'description' => 'Configure GrowCalc.',
    'access arguments' => array('administer growcalc'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('growcalc_settings'),
    'file' => 'growcalc.admin.inc'
  );

  return $items;
}

/**
 * Basic information for the page.
 *
 * @todo: Give links to admin pages, etc.
 */
function growcalc_info_page() {
  $content[] = array(
    '#type' => 'item',
    '#markup' => t('Nothing here'),
  );
  
  return $content;
}

function growcalc_init() {
  $attach = ((arg(0) !== 'system') && (arg(0) !== 'js') && (arg(0) !== 'admin') && (arg(0) !== 'field_collection'));
  $attach = $attach && !((arg(0) == 'node') && ((arg(1) == 'add') || ((is_numeric(arg(1))) && (arg(2) == 'edit'))));
  if ($attach) {
    if (($ember = libraries_load('ember')) && !empty($ember['loaded'])) {
      drupal_add_library('system', 'ui');
      drupal_add_library('system', 'ui.autocomplete');
      drupal_add_library('system', 'ui.dialog');

      drupal_add_js('sites/all/libraries/raphael/raphael.js');
      drupal_add_js('sites/all/libraries/sylvester/sylvester.js');

      drupal_add_js('sites/all/libraries/pnotify/jquery.pnotify.js');
      drupal_add_css('sites/all/libraries/pnotify/jquery.pnotify.default.css');
      drupal_add_css('sites/all/libraries/pnotify/jquery.pnotify.default.icons.css');

      drupal_add_js('sites/all/libraries/jquery.ui.spinner-master/ui.spinner.js');
      drupal_add_css('sites/all/libraries/jquery.ui.spinner-master/ui.spinner.css');

      drupal_add_js('sites/all/libraries/hammer.js/hammer.js');
      drupal_add_js('sites/all/libraries/hammer.js/jquery.hammer.js');


      drupal_add_js('sites/all/libraries/farbtastic/farbtastic.js');
      drupal_add_css('sites/all/libraries/farbtastic/farbtastic.css');

      drupal_add_js('sites/all/libraries/d3.js/d3.js');

      drupal_add_js(drupal_get_path('module', 'growcalc') . '/js/libs/jquery.list-filter.js');
      drupal_add_js(drupal_get_path('module', 'growcalc') . '/js/libs/ember-jquery-ui-mixin.js');
      drupal_add_js(drupal_get_path('module', 'growcalc') . '/js/libs/JSON.js');
      drupal_add_js(drupal_get_path('module', 'growcalc') . '/js/libs/color.js');

      drupal_add_css(drupal_get_path('module', 'growcalc') . '/css/growcalc.css');
      drupal_add_js(drupal_get_path('module', 'growcalc') . '/js/growcalc.js');
    }
  }
}

function growcalc_entity_new($type) {
  $entity = new stdClass();
  $entity->type = $type;
  $entity->status = 1;
  $entity->language = 'und'; //language_default()->language;
  $entity->created = time();
  $entity->timestamp = time();
  node_object_prepare($entity);

  return $entity;
}